[project]
name = "telemetry-boss-fight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "seagraves", email = "christopher.seagraves@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[project.scripts]
telemetry_boss_fight = "telemetry_boss_fight:cli"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
